export type AgentStatus = "active" | "paused" | "attention" | "risk" | "revoked";
export type TransactionStatus = "settled" | "pending" | "blocked" | "approval" | "approved" | "approval_required" | "failed" | "neutral";
export type ApprovalStatus = "pending" | "approved" | "rejected" | "failed";
export interface Agent { id:string; name:string; description:string; organization_id?: string; status:AgentStatus; walletAddress?:string; address?:string; wallet?:string; initials?:string; balance:number; dailyBudget:number; dailyLimit:number; monthlyBudget?:number; spentToday:number; todaySpend:number; dailySpent?:number; monthlySpent?:number; transactionLimit:number; txLimit:number; approvalThreshold:number; recipientAllowlist:string[]; recipients?:string[]; payments?:number; approvalsPending?:number; risk?:"low"|"medium"|"high"; lastActive?:string; createdAt?:string; }
export interface Transaction { id:string; agentId:string; agentName:string; agent?:string; amount:number; token?:string; asset?:string; recipient:string; recipientName?:string; purpose?:string; status:TransactionStatus; reason?:string; policyReason?:string; decisionTrace?:string[]; txHash?:string; memo?:string; time?:string; createdAt:string; }
export interface Policy { id:string; name:string; description?:string; agentId:string; agent?:string; active:boolean; enabled?:boolean; status?:"active"|"draft"; dailyLimit:number; dailyBudget?:number; txLimit:number; transactionLimit?:number; monthlyLimit?:number; approvalThreshold:number; approvalAbove?:number; recipients:string[]; allowlistedRecipients?:string[]; allowedRecipients?:string[]; blockedRecipients?:string[]; activeHours?:string; createdAt?:string; }
export interface Approval { id:string; paymentIntentId?:string; transactionId?:string; agentId?:string; agentName:string; agent?:string; amount:number; asset?:string; recipient:string; purpose?:string; reason:string; status:ApprovalStatus; priority?:"normal"|"high"; createdAt:string; decidedAt?:string; }
export interface Treasury { walletAddress?:string; walletMode?: "created" | "imported" | "connected" | ""; balance:number; allocated:number; available:number; spentToday:number; blockedRisk:number; agentAllocated:number; monthlySpend:number; }
export interface PaymentIntent { id:string; agentId:string; recipient:string; recipientName?:string; amount:number; asset:string; memo?:string; status:TransactionStatus; reason?:string; txHash?:string; createdAt:string; decisionTrace?:string[]; }
